namespace Scarif_DS_1.modulos
{
    public enum TipoDados
    {
        Count,
        AddPage,
        RemovePage,
        Split,
        WaterMark,
        Concat,
        Alternate,
        Create,
        Protect,
        Unprotect
        /*
        CaminhoOrigem,
        CaminhoOrigem2,
        CaminhoDestino,
        CaminhoDestino2,
        Pagina,
        Texto,
        MarcaAgua,
        Senha,
        PosicaoAdicionar,
        Fonte,
        Tamanho,
        Estilo,
        Alinhamento
        */
    }
}